name: Generate Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🟢 Contributors chart
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/contributors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          base: ""
          plugin_contributors: yes
          config_timezone: Europe/Moscow

      - name: 🔁 Activity chart
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          base: ""
          plugin_activity: yes
          config_timezone: Europe/Moscow

      - name: 📅 Timeline chart
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/activity-timeline.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_visibility: all
          config_timezone: Europe/Moscow
