name: Organization Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: junketsu
          template: classic
          base: ""
          plugin_activity: yes
          plugin_contributors: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_traffic: yes
          plugin_stars: yes
          plugin_people: yes
          plugin_followup: yes
          plugin_repositories: yes
          config_timezone: Europe/Moscow
          output: metrics
          
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update organization metrics"
          git push
