name: Generate Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    environment:
      name: TOKENS
    steps:
          
      - name: Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: metrics/repo-traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_traffic: yes
          
      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4

      - name: 📅 Timeline chart
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/activity.svg
          base: ""
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_visibility: all
          config_timezone: Europe/Moscow

      - name: Issue activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
