name: Organization Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    environment:
      name: TOKENS

    steps:
      - name: Generate activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          template: classic
          base: ""
          plugin_activity: yes
          config_timezone: Europe/Moscow
          output: metrics/activity.svg

      - name: Generate contributors
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          template: classic
          base: ""
          plugin_contributors: yes
          config_timezone: Europe/Moscow
          output: metrics/contributors.svg

      - name: Generate people graph
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          template: classic
          base: ""
          plugin_people: yes
          config_timezone: Europe/Moscow
          output: metrics/people.svg

      - name: Generate activity timeline
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Junketsu-stacking
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          config_timezone: Europe/Moscow
          output: metrics/activity-timeline.svg
